### ISSUE TITLE
Clone doesnt run

### ISSUE THREAD

**Issue by moafzalmulla** [oliger/react-week-calendar#1]
HI @oliger ! Great repo by the looks of it.

Just cloned but getting error, see screenshot : 
<img width="483" alt="screen shot 2017-09-08 at 12 13 50" src="https://user-images.githubusercontent.com/2478550/30209290-3ee12de6-948f-11e7-9911-0ab7db27c0ab.png">

**Comment by oliger** [comment]
Hi @tweetzal, I was not remembering this repo. I just tried it and it seems to work fine 😕 . I feel like `babel-preset-react` is somehow ignored... have you run `npm/yarn install`?

**Comment by moafzalmulla** [comment]
Tried both npm install and yarn install

**Comment by moafzalmulla** [comment]
Ok Got it, I had moved it from its repo folder - just recloned and it worked with npm install and npm start. Thanks for quick reply :)
